
// [

//   { id: 3, name: "Venusaur",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"},
//   { id: 4, name: "Charmander",  rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"},
//   { id: 5, name: "Charmeleon",  rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"},
//   { id: 6, name: "Charizard",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"},
//   { id: 9, name: "Blastoise",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"},
//   { id: 18, name: "Pidgeot",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png"},
//   { id: 20, name: "Raticate",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png"}.
//   { id: 22, name: "Fearow",     rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png"},
//   { id: 37, name: "Vulpix",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png"},
//   { id: 38, name: "Ninetales",  rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png"},

//   { id: 40, name: "Wigglytuff", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png"},
//   { id: 45, name: "Vileplume",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png"},
//   { id: 55, name: "Golduck",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png"},
//   { id: 56, name: "Mankey",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png"},
//   { id: 57, name: "Primeape",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png"},
//   { id: 58, name: "Growlithe",  rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png"},
//   { id: 59, name: "Arcanine",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png"},
//   { id: 61, name: "Poliwhirl",  rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png"},
//   { id: 62, name: "Poliwrath",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png"},

//   { id: 67, name: "Machoke",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png"},
//   { id: 68, name: "Machamp",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png"},
//   { id: 70, name: "Weepinbell", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png"},
//   { id: 71, name: "Victreebel", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png"},
//   { id: 73, name: "Tentacruel", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png"},
//   { id: 76, name: "Golem",      rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png"},
//   { id: 77, name: "Ponyta",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png"},
//   { id: 78,  name: "Rapidash",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png"},
//   { id: 80, name: "Slowbro",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png"},
//   { id: 83, name: "Farfetch'd", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png"},
//   { id: 85, name: "Dodrio",     rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png"},
//   { id: 86, name: "Seel",       rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png"},
//   { id: 87, name: "Dewgong",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png"},
//   { id: 91, name: "Cloyster",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png"},

//   { id: 102, name: "Exeggcute", rarity: "comum",    chance: 50, img:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png"},
//   { id: 103, name: "Exeggutor", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png"},

//   { id: 106, name: "Hitmonlee", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png"},
//   { id: 107, name: "Hitmonchan",rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png"},
//   { id: 112, name: "Rhydon",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png"},
//   { id: 113, name: "Chansey",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png"},
//   { id: 115, name: "kangaskhan",rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png"},
//   { id: 122, name: "Mr. Mime",  rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png"},
//   { id: 123, name: "Scyther",   rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png"},
//   { id: 124, name: "Jynx",      rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png"},
//   { id: 126, name: "Magmar",    rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png"},
//   { id: 127, name: "Pinsir",    rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png"},
//   { id: 128, name: "Tauros",    rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png"},
//   { id: 130, name: "Gyarados",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png"},
//   { id: 131, name: "Lapras",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png"},
//   { id: 132, name: "Ditto",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png"},
//   { id: 136, name: "Flareon",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png"},


//   { id: 139, name: "Omastar",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png"},

//   { id: 141, name: "Kabutops",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png"},
//   { id: 142, name: "Aerodactyl",rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png"},
//   { id: 143, name: "Snorlax",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png"},
//   { id: 144, name: "Articuno",  rarity: "lendario", chance: 5,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png"},

//   { id: 146, name: "Moltres",   rarity: "lendario", chance: 5,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png"},
//   { id: 147, name: "Dratini",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png"},
//   { id: 148, name: "Dragonair", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png"},
//   { id: 149, name: "Dragonite", rarity: "raro",     chance: 8,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png"},
//   { id: 150, name: "Mewtwo",    rarity: "lendario", chance: 3,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png"},
//   { id: 151, name: "Mew",       rarity: "mistico", chance: 3,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png"},
// ];