
// [

//   { id: 3, name: "Venusaur",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"},
//   { id: 6, name: "Charizard",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"},
//   { id: 9, name: "Blastoise",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"},
//   { id: 18, name: "Pidgeot",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png"},
//   { id: 22, name: "Fearow",     rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png"},
//   { id: 40, name: "Wigglytuff", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png"},
//   { id: 45, name: "Vileplume",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png"},
//   { id: 56, name: "Mankey",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png"},
//   { id: 57, name: "Primeape",   rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png"},
//   { id: 67, name: "Machoke",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png"},
//   { id: 68, name: "Machamp",    rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png"},
//   { id: 70, name: "Weepinbell", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png"},
//   { id: 71, name: "Victreebel", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png"},
//   { id: 76, name: "Golem",      rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png"},
//   { id: 83, name: "Farfetch'd", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png"},
//   { id: 85, name: "Dodrio",     rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png"},
//   { id: 102, name: "Exeggcute", rarity: "comum",    chance: 50, img:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png"},
//   { id: 103, name: "Exeggutor", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png"},
//   { id: 106, name: "Hitmonlee", rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png"},
//   { id: 107, name: "Hitmonchan",rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png"},
//   { id: 108, name: "Lickitung",  rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png"},
//   { id: 112, name: "Rhydon",    rarity: "incomum",  chance: 30, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png"},
//   { id: 113, name: "Chansey",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png"},
//   { id: 115, name: "kangaskhan",rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png"},
//   { id: 122, name: "Mr. Mime",  rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png"},
//   { id: 123, name: "Scyther",   rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png"},
//   { id: 127, name: "Pinsir",    rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png"},
//   { id: 128, name: "Tauros",    rarity: "raro",     chance: 15, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png"},
//   { id: 132, name: "Ditto",     rarity: "comum",    chance: 50, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png"},
//   { id: 139, name: "Omastar",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png"},
//   { id: 141, name: "Kabutops",  rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png"},
//   { id: 142, name: "Aerodactyl",rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png"},
//   { id: 143, name: "Snorlax",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png"},
//   { id: 147, name: "Dratini",   rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png"},
//   { id: 148, name: "Dragonair", rarity: "raro",     chance: 10, img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png"},
//   { id: 149, name: "Dragonite", rarity: "raro",     chance: 8,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png"},
//   { id: 150, name: "Mewtwo",    rarity: "lendario", chance: 3,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png"},
//   { id: 151, name: "Mew",       rarity: "mistico", chance: 3,  img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png"},
// ];